permalink: pretty
defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
  - scope:
      path: ""
      type: posts   # only true for posts
    values:
      is_post: true # true for all posts
